# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run.mac

# Verbose
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/control/verbose 0


/gps/particle neutron
/gps/ene/type Mono
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
/gps/pos/centre 0. 0. 10. cm
/gps/pos/radius 2. cm
/gps/direction 0. 0. -1. cm
/gps/energy .025 eV






/run/beamOn 1000000


